// Generated by surrealql-analyzer — do not edit.
//
// Types only: nothing in this file exists at runtime. The client is a separate
// import, parameterised by what is declared here.
//
//   import { createClient } from "@surrealdb/analyzer-client";
//   import type { Queries } from "./surrealql-analyzer";
//
//   export const db = createClient<Queries>({ url });
//   const [people] = await db.query("SELECT name FROM person");
//
// Value conventions name what the SurrealDB SDK actually decodes, which is its
// own value classes: record links are `RecordId<"table">`, uuids are `Uuid`,
// durations are `Duration`, decimals are `Decimal`. Datetimes are a native
// `Date` because `createClient` sets `codecOptions.useNativeDates`. `NONE`
// fields are optional keys. Anything crossing a serialisation boundary (SSR, a
// `fetch` response, `JSON.stringify`) goes through `Json<T>`, which maps
// `RecordId<"team">` to `` `team:${string}` `` and `Date` to `string`.
//
// The classes matter beyond reading: a `RecordId` parameter encodes to a
// record link on the wire, while a plain string encodes to a SurrealQL
// string, so `WHERE team = $team` matches only with the class.
//
// To type `db.query("…")` on a client built WITHOUT the type argument — and
// the Svelte `<Query q="…">` markup form, which has no call to put one on —
// add this once, in your own code:
//
//   declare module "@surrealdb/analyzer-client" {
//     interface SurqlRegistry extends Queries {}
//   }

import type { RecordId } from "@surrealdb/analyzer-client";

export interface Person {
  id: RecordId<"person">;
  age: number;
  name: string;
  team: RecordId<"team">;
}

export interface Team {
  id: RecordId<"team">;
  name: string;
}

/** Every table in the schema, keyed by its SurrealQL name. */
export interface Tables {
  person: Person;
  team: Team;
}

/**
 * Every analyzed query, keyed by its exact text. Hand it to
 * `createClient<Queries>(…)`; a key that is not here is a type error at
 * the call, carrying its own remedy.
 */
export type Queries = {
  "SELECT id, name, age, team FROM person": { result: [Array<{ age: number; id: RecordId<"person">; name: string; team: RecordId<"team"> }>]; params: Record<string, never> };
  "SELECT id, name FROM person WHERE team = $team": { result: [Array<{ id: RecordId<"person">; name: string }>]; params: { team: RecordId<"team"> } };
  "SELECT name FROM person; SELECT age FROM person": { result: [Array<{ name: string }>, Array<{ age: number }>]; params: Record<string, never> };
  "CREATE person SET name = $name, age = $age, team = $team": { result: [Array<{ age: number; id: RecordId<"person">; name: string; team: RecordId<"team"> }>]; params: { age: number; name: string; team: RecordId<"team"> } };
};
